name = input("what is your name:")
last_name = input("what is you last_name:")
do_math = int( input("x:"))
do_math1 = int(  input("B:"))
print(name,last_name)
print(do_math+do_math1)

math = int(input("X:"))
math1 = int(input("B:"))
math2 = int(input("X:"))
math3 = int(input("B:"))
math4 = int(input("X:"))
math5 = int(input("B:"))
math6 = int(input("X:"))
math7 = int(input("B:"))
print(math+math1)
print(math2-math3)
print(math4/math5)
print(math6*math7)
